Forgot to push commit for Tunernome
AEFeinstein/Super-2023-Swadge-FW pull request #228
Opened 2022-11-07 06:13 UTC by haloflooder

Forgot to push out major changes
- Added subdivided beat system

Also put in some bug fixes:
- Changed position of metronome arm and size
- Sync beat systems when changing BPMs
- Fixed spacing between beat circles (cast some vars to a float)

2022-11-07 12:49 UTC, AEFeinstein commented on main/modes/mode_tunernome.c
> +        case 0: tunernome->usPerSubBeat = tunernome->usPerBeat; break;
Not requesting a change, but you could math this to be a single
```C
tunernome->usPerSubBeat = tunernome->usPerBeat / (1 + tunernome->subdividedBeats);
```

2022-11-07 13:16 UTC, AEFeinstein commented on main/modes/mode_tunernome.c
> +static const char rightStrTunerSel[] = "Sel: SubBeat";
It would be nice if this listed the number of subbeats similar to how the number of beats are listed.

2022-11-07 13:17 UTC, AEFeinstein commented
I was playing around with this on a physical swadge and experienced two crashes. I don't know why, but this branch is not getting merged until the issue is well known and fixed.

2022-11-07 13:41 UTC, AEFeinstein requested changes
Identify and fix crash before merge

2022-11-09 02:34 UTC, haloflooder commented
Couldn't reproduce the crash on the emulator but it happens on hardware. Decided to leave this feature out during the meeting.

2022-11-09 02:34 UTC, closed without merging