Paint undo
AEFeinstein/Super-2023-Swadge-FW pull request #342
Opened 2022-11-26 04:08 UTC by dylwhich

Uses SPIRAM to allow up to 984 actions to be undone!
I renamed the linked list implementation used by the emu (`emu/src/list/list.h`) from `list_t` to `linked_list_t` because both that and the `list_t` from `main/utils/linked_list.h` ended up included in the main and caused conflicts.

2022-11-26 20:31 UTC, AEFeinstein commented
Without even reading the changes, I do not like multiple linked list implementations in the same source. Any reason not to remove the implementation in `emu` entirely? I probably copied it from the IDF to get things off the ground...

2022-11-26 20:37 UTC, AEFeinstein approved these changes
Other than the list thing, seems fine. A few functions got returns without updated doxygen, if you care about that sort of thing.

2022-11-26 20:37 UTC, AEFeinstein requested changes
Other than the list thing, seems fine. A few functions got returns without updated doxygen, if you care about that sort of thing.

2022-11-26 21:35 UTC, dylwhich commented
> Without even reading the changes, I do not like multiple linked list implementations in the same source. Any reason not to remove the implementation in `emu` entirely? I probably copied it from the IDF to get things off the ground...

Ah sure, I can do that. I just didn't want to swap it out without knowing the rationale.



> Other than the list thing, seems fine. A few functions got returns without updated doxygen, if you care about that sort of thing.

Oops, I meant to do that and forgot. Will fix

2022-11-27 16:56 UTC, AEFeinstein requested changes
Maybe do some valgrind or asan to exercise the linked list and paint changes too?

2022-11-27 16:56 UTC, AEFeinstein commented on emu/src/emu_sensors.c
> +	clear(buttonQueue);
Copy paste bug

2022-11-27 17:40 UTC, AEFeinstein approved these changes

2022-11-27 17:40 UTC, merged