Replace text entry caps, shift, tab, backspace symbols
AEFeinstein/Super-2023-Swadge-FW pull request #351
Opened 2022-11-28 09:06 UTC by Brycey92

Also split shift and caps lock button functions!

Closes #310

2022-11-28 15:31 UTC, AEFeinstein commented
Visual diff:
![kbdiff](https://user-images.githubusercontent.com/231180/204317100-076bd30c-48f5-480d-9058-3a01f7f4023f.gif)

2022-11-28 16:08 UTC, AEFeinstein requested changes
Unrelated to these changes, I found a keyboard bug.
`textEntryInput()` only handles `KEY_ENTER`, `KEY_SHIFT`, `KEY_CAPSLOCK`, and `KEY_BACKSPACE`.
It *does not* handle `KEY_TAB`, `KEY_SPACE`, or `KEY_EOL`.
`KEY_SPACE` is fine because that's just the ASCII space char. `KEY_EOL` is used for drawing, but is not clickable, so that's fine too.
`KEY_TAB` is clickable, and while it is the ASCII tab char, that char isn't in the font, so after you tab, other letters you enter aren't visible.
Unless you have a better idea, `KEY_TAB` should get handled separately in the switch and a space char should be inserted instead of a tab.
```C
typedef enum
{
    KEY_SHIFT     = 0x01,
    KEY_CAPSLOCK  = 0x02,
    KEY_BACKSPACE = 0x03,
    KEY_SPACE     = 0x20,
    KEY_EOL       = 0x05,
    KEY_TAB       = 0x09,
    KEY_ENTER     = 0x0A,
} controlChar_t;
```

2022-11-29 00:04 UTC, Brycey92 commented
Thanks for the visual diff! 😄 

I just pushed your suggested tab fix, since that sounds like a good solution to me

2022-11-29 02:41 UTC, AEFeinstein approved these changes

2022-11-29 04:15 UTC, merged